; generated by Slic3r 1.1.5 on 2014-10-23 at 19:05:23

; perimeters extrusion width = 0.30mm
; infill extrusion width = 0.80mm
; solid infill extrusion width = 0.80mm
; top infill extrusion width = 0.60mm

G21 ; set units to millimeters
M104 S200 ; set temperature

T1
M109 S200 ; wait for temperature to be reached
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M106 S153 ; enable fan
G1 Z20
G1 Z20.2
G1 X1 Y1 F18000.000 ; move to first perimeter point
G1 X20 Y20 E2.03262 F1080.000 ; perimeter
;G1 X2 Y2 E0.35882 ; perimeter
;G1 X1 Y2 E0.09679 ; perimeter
;G1 X1 Y1 E0.09589 ; perimeter
